name: update-lambda-code

on:
   push:
      branches:
         - "main"

jobs:
   update-lambda-code:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Configure AWS Credential
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-northeast-1
         - name: Zip the handler file
           run: zip -r handler.zip handler.js
         - name: Update lambda code
           run: aws lambda update-function-code --function-name serverless-chatapp-lambda --zip-file "fileb://handler.zip"
